### ISSUE TITLE
[Feature Request] Purge data structures while importing

### ISSUE THREAD

**Issue by Toesmasher** [oratory/wago.io#102]
When exporting a WA as a string it includes *everything*, including personal preferences such as the contents of aura_env.config. Would it be possible to provide options to remove certain structures when importing an aura? When I'm exporting my auras for public use, I generally don't want my options to become my users' options, rather I want the default values specified in the custom options tab to apply.

Another such structures that maybe interesting to remove from the imports are animations.

As it is, I find myself editing my auras in the built-in editor to remove these structures after every import, which gets tedious.

**Comment by oratory** [comment]
This is the intended behavior in the addon so I'm not inclined to make a change that would impact all the imports on the site to go against that.
If you want to export with defaults the easiest way would be to duplicate the aura, change to default and then export that version.
