### ISSUE TITLE
[Maybe] Version seems bugged after rev. 150

### ISSUE THREAD

**Issue by pquerner** [oratory/wago.io#11]
I reported this on Sunday 10 December at around 7:23 PM on the Weakauras Discord. I cannot hardlink this sadly (I dont know how, or its not possible).

In this weakaura here https://wago.io/SJ92um5LW the revision count is at 241 currently, but the version the editor reports is stuck at 150. Therefore you never really know what revision you just imported is.

Here is what I found so far:
- Its not stuck to Browser session. Completely new browser and "private tab" is the same issue.
- The actual WA string differs from version 150 to say latest version. So something *is* changing. Just not the "version" data field.

I dont know who defines the "version" field. 

Here is the conversation so far (what I could grasp) that happend on the Discord channel:

```

air - Last Sunday at 7:23 PM
@Ora does the iteration count stop working at or after 150 iterations? https://wago.io/SJ92um5LW this WA is at iteration version 205, and yet the importer (ingame) still shows version 150. not sure if I grabbed version 150 now or 205. (I tried with new browser aswell, same version)
T21 Antorus Auras (11/11 Bosses, all difficulties) | Wago.io
Update it shortly before antorus launch!!! check out bit.ly/newraid for antorus mechanics/guide Enable "Interface->Action Bars-> Show Numbers for

Ora - Last Sunday at 7:24 PM
it doesn'
doesn't stop at 150
I'm just testing to confirm that nothing weird is going on
but it sounds like you have version 150 installed
hmmm its using 150 for me too
that is weird!

air - Last Sunday at 7:29 PM
maybe problem in the addon, not on your end

Ora - Last Sunday at 7:32 PM
I think the website is not updating the url properly

air - Last Sunday at 7:36 PM
mh the WA string is fine. but it somehow shows version 150 in the table
WA string 150 differs from 205 tho. so its "new" except the version field.
```

**Comment by oratory** [comment]
This problem is fixed going forward but existing imports will still have the old URL until they are updated. Will need to create a script to batch update things when necessary.

**Comment by pquerner** [comment]
https://wago.io/HJO1zKFWG is not having a "url" data field, dont know if thats on purpose or somehow the fault of your change.

**Comment by pquerner** [comment]
Something is off here.
https://wago.io/SypgpjRSW/6 displays version 5, when revision 6 is latest. Is it not being updated by the addon or your page?

**Comment by oratory** [comment]
Cleaning up some old tickets, this was done a while ago.
