### ISSUE TITLE
Cannot login with Battle.net if I don't allow profile access

### ISSUE THREAD

**Issue by NLZ** [oratory/wago.io#12]
When I authorize WAGO.IO for my Battle.net account, it asks for:
- Your Blizzard Account ID and BattleTag - mandatorily
- Your World of Warcraft profile - optional

Back in the day I haven't allowed the profile, only the ID.
But something changed in the last couple of months since I logged in, maybe this anti-spam business.
Since then I get an "An error occurred." when I try to login.

Guess it should be changed to make profile request mandatory, and maybe a more verbose error message for existing users.

**Comment by pquerner** [comment]
Its unclear where you get the "An error occurred" message from. If its Blizzard, you can revoke access on battle.net and then reallow it by requesting new access from wago.

**Comment by NLZ** [comment]
When you allow the battle.net access, you can optionally select the profile sharing towards wago. But it is not optional, because otherwise it wont log in to wago.

**Comment by oratory** [comment]
Thanks for the report, this is fixed.
