### ISSUE TITLE
TBC Weakaura category

### ISSUE THREAD

**Issue by karin1337** [oratory/wago.io#132]
TBC Weakauras seem to have a limited amount of categories. I am only able to select classes or group roles as category. I have a weakaura for fishing and i cant select secondary professions.

**Comment by Zyin055** [comment]
Came here to post this. I can only add class and group role categories to my uploaded weakaura. https://imgur.com/a/NXLuOzP

**Comment by oratory** [comment]
Thanks for the reports, this is now fixed.
