### ISSUE TITLE
might need to do somethign about Spaten on discord

### ISSUE THREAD

**Issue by fubar187421** [oratory/wago.io#136]
I posted

 

Trying to make an aura to display if I have a growl on in instance/raids and when I turn it off the icon diapers then when not in a raid or instance the aura tells me to turn growl back on then diapers again.

 

https://wago.io/MYkuiHauh

 

I can get it to load and work when I zone into instance/raids but not when I zone out of them.

 

on the discord page. didn't know what one to post it in so posted it in 2 or 3 location. Spaten deleted them all and yelled at me for posting in multi-locations but as I said didn't know where to post it. but instead of him saying you have posted it too many times and in the wrong location and then give me the correct location to post it, he deleted them all and started yelling at me to act like a human. that alone is disrespect. then he bans my account after I called him out on his rude ways along with Cosmo was trying to troll by being rude as well. so he bans deletes and blocks someone trying to get help but lets the person stay that is being rude and destroying the community. Both Spaten And Cosmo need removed ban and blocked along with Spaten removed from the payroll. As anyone in California that acted this way would have lost their job for mistreating a customer. so I made a new account to try and get help still and when I posted the link again in the one location he left my other one before he bans that account he deletes it and bans that account too. no reason to act like this to anyone trying to get help. as this is the only place to get help with WeakAura Creating.

**Comment by mrbuds** [comment]
https://www.google.com/search?q=find+a+psychiatrist+near+me

**Comment by oratory** [comment]
1. This is a repo for Wago.io, not a dispute forum for a discord server.
2. You were banned for breaking the Discord server's rules and then cussing out a mod who was telling you not to spam.
