### ISSUE TITLE
Trying to Figure out How to..

### ISSUE THREAD

**Issue by fubar187421** [oratory/wago.io#137]
Trying to make an aura to display if I have a growl on in instance/raids and when I turn it off the icon diapers then when not in a raid or instance the aura tells me to turn growl back on then diapers again.

 

https://wago.io/MYkuiHauh

 

I can get it to load and work when I zone into instance/raids but not when I zone out of them.

what am I doing wrong and how can I fix it.

**Comment by oratory** [comment]
This repo the code base for the Wago.io website, not for WeakAuras. Check the WA wiki https://github.com/WeakAuras/WeakAuras2/wiki#load
