### ISSUE TITLE
Cannot put external link to my wago page.

### ISSUE THREAD

**Issue by hobulian** [oratory/wago.io#138]
I published my WeakAuras today at Wago.io.

I created a description and in that description I used links to external websites.

But when you click on that link it just redirects you to the same wago.io page. 

I even connected my blizzard account to my wago account now. But why can't i put external link?

**Comment by oratory** [comment]
Connecting a B.net account with a max level character (though not in classic/tbc) should flag you as "human" and let you use links. What's your Wago account name? I'll check what's up or fix it manually.

**Comment by hobulian** [comment]
my account name is "호불" in korean.

**Comment by oratory** [comment]
I see a "no characters found" error implying no Shadowlands characters or some Bnet error, but I updated your account so your links will work now.
