### ISSUE TITLE
Bug: Multiple embed present (and more are added)

### ISSUE THREAD

**Issue by WFrancois** [oratory/wago.io#143]
Heyas!

I think there's an issue with the new embed widget, where it can append multiple widget of the same stream :/

I figure it's here https://github.com/oratory/wago.io/blob/881c28ec1d400a41a6cba093fd17425ad530e711/frontend/src/components/UI/StreamEmbed.vue#L91, but as I'm unsure what's the data input, I can't really pin point what's the issue.

I guess the issue is that calling `window.Twitch.Player` each time will create a new embed each time instead of only one? (unsure, would need testing)

Here's an example I have on my machine, on first load you have at least two embeds, but as time goes on, it looks like more are added :/ (I was able to see four at one point)

![image](https://user-images.githubusercontent.com/5872952/131389020-5630e4e2-ed6d-433c-9ae9-cbcbfd8fa211.png)

**Comment by oratory** [comment]
Thanks! This is now fixed with https://github.com/oratory/wago.io/commit/f23adcfea5b4807b9008728635ab0631f1e2c588
