### ISSUE TITLE
Add to/Remove from/Create Collection icons invisible in Dark theme

### ISSUE THREAD

**Issue by amiyuy** [oratory/wago.io#18]
Light theme:
![image](https://user-images.githubusercontent.com/3958649/43656718-435dd5dc-9708-11e8-8cab-7ce437540bb3.png)

Dark theme:
![image](https://user-images.githubusercontent.com/3958649/43656713-3bdbc1a2-9708-11e8-855f-423c1caa1a9e.png)

**Comment by oratory** [comment]
Cleaning up some old tickets, this was done a while ago.
