### ISSUE TITLE
Empty collection displays list of newest uploads

### ISSUE THREAD

**Issue by amiyuy** [oratory/wago.io#19]
Collection: https://wago.io/HJEsWIMHQ

![image](https://user-images.githubusercontent.com/3958649/43668018-90330e8c-972f-11e8-9f6c-6128da025281.png)

![image](https://user-images.githubusercontent.com/3958649/43668033-a4e625f8-972f-11e8-83d7-e7d35a892b31.png)

I would expect it to be empty.

**Comment by oratory** [comment]
Cleaning up some old tickets, this was done a while ago.
