### ISSUE TITLE
WA Companion will not update

### ISSUE THREAD

**Issue by reaper082** [oratory/wago.io#196]
![Screenshot (6)](https://user-images.githubusercontent.com/109622541/179924677-96632219-b9fd-4219-8a19-1b38b8500ebd.png)
The companion addon will not update. I have uninstalled, reinstalled, and attempted to update numerous times to no avail.

**Comment by oratory** [comment]
This should be posted to the WeakAuras Companion team: https://github.com/WeakAuras/WeakAuras-Companion
