### ISSUE TITLE
[Enhancement] Make font larger

### ISSUE THREAD

**Issue by N6REJ** [oratory/wago.io#199]
idk where to put this so please forgive me if this is the wrong place.  Could we somehow make this font larger.  Even on a 42" screen its micro print.
<img width="686" alt="image" src="https://user-images.githubusercontent.com/1850089/181196269-86fffa77-86be-48d8-b47b-52aeb305c275.png">
I admit I'm an old man so my eyes are not the greatest.
But I think you can see its extremely tiny.
![WoWScrnShot_072722_031400](https://user-images.githubusercontent.com/1850089/181197257-85130a08-b5bd-49e6-bcd5-721bd979b58f.jpg)

**Comment by oratory** [comment]
The WeakAuras team has their own repo over here: https://github.com/WeakAuras/WeakAuras2
