### ISSUE TITLE
Evoker spec load&trigger filter causes wago to remove all checkboxes in that setting

### ISSUE THREAD

**Issue by Reloe** [oratory/wago.io#206]
When making an Aura that has any of the evoker specs selected under the "Class and Specialization" load OR used in a trigger and filtering by these specs will cause wago to uncheck all spec boxes.
This doesn't happen when sharing the aura ingame or exporting -> deleting -> importing so that means it should be a wago issue.
Here are is an aura, once in a wago link and once directly with the string. When importing it from wago all the checkboxes are removed, when importing the string directly they stay checked.
There are 3 auras in this, the battle shout one working as intended, Arcane Intellect having evoker specs selected in the trigger and Blessing of the Bronze having evoker specs selected in load: 
https://wago.io/hJx1HfPcX

!WA:2!1A5wZXXrvCCTSoe8aeTETLITsa2ySmXgWsYxKTCfGOrELLS1Tm7klFby7EMP3TN4zNzCp9OBGXXYjgXftiRtc3lOwmVXduQsXZuQYRuCyXFcCLx5fv8E40ZmRSKTbk)aVmZ0N(0xoN(35FpzUq(qJtCK(pYjYxpVDE7v3)dm9f2mHo16Q2c)GGC6UolVmvyxOSVVR0jWCbAn)XptJGbo)KNR2KxCGw0ij3xmDG0X3lutS00vRgYKJ9Qx7V0XR2rh6Rr9SW(NX3XtAosXPkx0yTKfzeFxFX5YKjt2JgjCdEbUugeE6(6tTchXXVVnxI(gqqTIN(bncLuHuZSQJNtixthFj1wrkCQvJjc75GI0pVDtBMzu1QLxkGjgR4eZm6StOlXgg0ib9ORegWCDh3ou7bHrMS5zEYsO3olUwLrgUu5kLkpSrz9iCYndCPlXeB62mcg6MrPzkoXegXwmhJrDLCdpADwOwJiV0TG2gyeZeEu3lGBnC3VqdQNtDQkqgeEUrxNrdzLKcMxnj)zHU0989yTSXTNYJkQnRiKz57zhUIYvvOa9QxN64nkCaCaqVWbHVe8Y47oFulI5twZSnXnUbRw8zJURp1Eu9qNLzDBupcpo10XeHv3Wr0mSCPHHQVmLuxmSuF2YmLdsoQYMn7mzryXm0psyXmDQh4lKgHw4aYAMCOYBM8UODnwWUkDTiQGvy0ix3cZXDKSMI49IkwmQj8JcsDVeUNEM1t(obG2PziRogfgdG8z)nL(wPH0EZC7M73XUXCiMuOmluUwvbM6XmjvsZUrcUnQYKAvmlnIrXItLICJ7HZmIBo2RDz3HVKt08oV8ON1etYvDQPjwSn7g8N64gF8hF)MQSVtcyVMJxvFrYXNwJqMB1yKg2zERtV6HB6GUwkoT8IDa7aEg4zZaFkyNTSWYgB)f8kTGtaJSE7MQ0dxxnicSRN7Gq(v33dIcztsLw8kw(ieXvTpRkfL0M0eRbIOULWdSv76F1jrMJ8HDsUd5Di75aK3M83jVf545i)nY96K8rDsod2BoYDjLpaPCoY9Zr(Goj3VtYk4KoI6KMd9aNETApC(1hO)(7ny3BXY0iasL(I8VYgo188fSX9M3j0X0LrGDd7Pzi3FHrCrOnK3mXHZWO2Kw4sm8MBvcSxyFnufDj1hqbn4ZdFbKv7oiF6OCcX8GhZsYSjWlcFo451e4KmfoaEJQmmLy47Y4RRML4cxh7WE0hCWtESwj9sDSNKkUkFdCufxeZtLskVjWlPfSlL2X8SYjvLt6BZ(JDa7FHnUkJfmSc)LgQdvo8fvvLpAL1H(FxRHsnHuPQULXHdNf(YNUBORwyDNQ6rLp9SxfdwjBrzLqofp(VycNLjyFXgJFKaxvct)a6TXM9f0tVkPOruhkf6RqV1PloB72bh4XMIT29MZwqUTS(pu59bjwBtZ6dpB5Pd2DSrux3xH7wZ5yl56dJn3izzCwKzhB8MTsQ2UuA8SEC)VEuO0P6sWoBk8LysPmAuFQPNQi0LaZkkFAg7OvBvLSns3)y8KBuHZYfETiQTQEUq5YBlZ1ELAfBBbSOEobnyL5s)O1MZtSW)0ZwEIXNQyASVLlIWcZn9uj9muWl9yPXOhlhMgTxCBrB7sIQTsKyQ4N0BQItfLAB2uLT0iooXNAP9WB7odfgGtbD1qXpXMm5mNAC5DGVY8QQ34jK)Gy5AmKSRKQGp4DrrG3HadOeUdYR8C7(WH(uDb9h)8RIp)ZReAX8OchFYrLmpst5cOW)svXQfYkyqlxQo1JSIcSTdMpaT5YwmE32m2gkT7rjgb4nYlrmsAzMmhKJQgaCm44WNflR0Go1GCD3W2VIfsh(15WqW0R0wnKdJRbFsn4tdFg4SA6l77xxDrZaGomIb1nGtZgSN2oRWjuYGI7dBo81GVo8nsVsiyx6uP0LvOe3pswqI3nadNnoxms6GXYFSANrmwqXV3bglduCn)zgl4qhk6qZojx44PUMHXnEiC2ehF6F)WxZ2ju9hbJJkw79tSJ)jCon48Wox9WWeBt3hMKatXHP3uDhMHdxrdmwD325iFuoY1j3GCtYoYrEtLM9)GSNCK3nh5a5i3dLQVc5dVc5dYrUf5VI66qjESQyzywLUlmhbUq(xbUih(wCOsp6dC8tmeysGxlwRnwD9se4BsusTpVMsPf(2C4YeGgl6JAIGvSeiy3w0tPMHIABr07rS05JzzlADq1v7gQLb4Ozh41HRIVDJPCOo4b(qaCTBcImqiMyKqeoI5HfIZTWIWsWYzGVd8DHRdFp4gOh3Ia3eNHvYaVXqvH3md8wzHBNmDFFcSQQ6a(bWpuvqa)io8JvW)nX051tH)uo)o8TI6WpHaVnb(PeaRrAqG3JaVlbUlbEFc8ZiWpFRSAUUHFbxrSiJc)YTdNWVAtYe(1zHFZJqGDnSWI6Xkmo(RFUU4DlTPq43sGFxkVzpXq8z5dx8qNFuOjh(9jzI7XH)WtdsTxfsHN5xMRae8SwXhBHnIVKgmrerdUspMh7udCYJD0y6qbtiEGqYdXdfyG8HcGEc8Xt)LI)FKpEJHAZh3I8FNpUnwoh)dnATbLrXAlSGzWtf)8KQ6SuOP)TJoprO5UXqZ79eHMoBZnp9qZlO7YcdXTAb)QfKCwbDHV3YSNe6mjBkX1U85o5yNN)FgDYp)9V4)(

**Comment by oratory** [comment]
Fixed with https://github.com/oratory/wago.io/commit/0667e30105e7485fa029643b6a0b5eb3c1915396 thanks.
