### ISSUE TITLE
[Export] Version number not always updated correctly

### ISSUE THREAD

**Issue by amiyuy** [oratory/wago.io#23]
![](https://cdn.discordapp.com/attachments/273144328447197186/483333059870064650/unknown.png)

https://wago.io/spellCounter has 4 versions, but Version # tooltip in-game says 2.

> [12:12 PM] rivers: https://github.com/WeakAuras/WeakAuras2/commit/5972bebe8ff287cd7e46cca8f9723bded90aee01
> [12:13 PM] rivers: @AmiYuy talk to ora about the version field not working properly

**Comment by oratory** [comment]
Cleaning up some old tickets, this was done a while ago.
