### ISSUE TITLE
luacheck

### ISSUE THREAD

**Issue by yuqo2450** [oratory/wago.io#236]
If I am correct, you run `luacheck` for all custom code.

I am developing and maintaining some custom code auras and was thinking about adding code linting to my CI pipeline as well. So far I haven't found the correct configuration to ignore _the error that requires a function to have a name_.

To me it seems you have solved this issue. So my question is could you give the `luacheck` config used on the website?

**Comment by oratory** [comment]
Wago does actually name all the anonymous functions while building a single file with all the custom code strings that it runs luacheck on. 

https://github.com/oratory/wago.io/blob/master/backend/api/helpers/luacheck.js#L31-L33
