### ISSUE TITLE
[Discord] Bot notifications for updates and mentions not working

### ISSUE THREAD

**Issue by amiyuy** [oratory/wago.io#24]
- 8/25 - I got a comment on 8/23 but no Discord notification.
- 8/26 - No Discord notifications today when rivers updated an aura I have favorited twice.
- 8/26 - Reloe: got a comment on one of my auras today but haven't receieved a message from the bot, worked in the past and I didn't change any settings

**Comment by Gabb1995** [comment]
Can confirm same for me,
Whenever I refresh the Account page, the 2 options are off even though I turn them on.

**Comment by amiyuy** [comment]
Working as of two days ago.

**Comment by Gabb1995** [comment]
Can confirm!
