### ISSUE TITLE
[Feature Request] Method Dungeon Tools import area

### ISSUE THREAD

**Issue by Tacita-Era** [oratory/wago.io#26]
Mythic+ have become a core part of the gameplay experience. Method's dungeon tools addon allows people to plan and share routes. It has import strings similar to WA, and it'd be nice to have an organised, well-known area to find and share these tidbits.

**Comment by Sooleawa** [comment]
I am not a mythic+ person but i also see benefit in this idea.

**Comment by oratory** [comment]
Cleaning up some old tickets, this was done a while ago.
