### ISSUE TITLE
Errors with comments

### ISSUE THREAD

**Issue by mrbuds** [oratory/wago.io#35]
While typing a reply in comments i had 2 problems.

![preview](https://i.imgur.com/yxKmIbm.png)

- while writing at one point there was some background operation done which resulted in the first 2 lines of the screenshot above
- when i press "submit" the comment doesn't show on screen but disappear, making it look like i wasted my time writing it, and showing the 3rd line of error. After refreshing the page with F5 the comment shows.

**Comment by oratory** [comment]
Cleaning up some old tickets, this was done a while ago.
