### ISSUE TITLE
Add Table Data code diffs

### ISSUE THREAD

**Issue by jjholleman** [oratory/wago.io#91]
Currently code diffs only shows diffs from custom code blocks.   
I'd love to see code diffs implemented for table data too.  
Why?: many authors fail to provide a descriptive changelog when they update non-custom code block settings in their exports, leaving the importing user questioning what has changed.  
Showing table data diffs should give the user some information about the changes the author made.

**Comment by oratory** [comment]
Table data is now sorted by key for readability and it makes this possible, so this is added in (for future imports/versions). 👍
