### ISSUE TITLE
[Bug] Copying an import string can copy the string "false"

### ISSUE THREAD

**Issue by Toesmasher** [oratory/wago.io#99]
It's possible to click the "COPY WEAKAURA IMPORT STRING" button and simply have the string "false" be copied to the clipboard. Going to the Editor tab, clicking "EXPORT/FORK CHANGES" and copying the string from there works just fine.

Example: https://wago.io/H5QS5WvgH/1.0.5 - Specifically version 1.0.5 will simply copy the string "false", other versions appear to work just fine.

**Comment by oratory** [comment]
Very strange one, I've never seen that before and I can't replicate it locally. Added a check to retry processing if encoding returns false so I hope that fixes it.

**Comment by Toesmasher** [comment]
At first I thought it might've been a browser problem, but I managed to replicate the exact same issue in both firefox and chrome. It seems to be fine after your fix!

**Comment by oratory** [comment]
This seems to have been fixed at some point. :)
